'use client'
import React, { useState } from 'react';

const DateTimeDropdown = ({ name }) => (
  <input type="datetime-local" name={name} className="w-full border px-2 py-1" />
);

const BillOfLadingForm = () => {
  const [pickupZip, setPickupZip] = useState('');
  const [deliveryZip, setDeliveryZip] = useState('');

  const handleZipChange = (setter) => (e) => {
    const value = e.target.value.replace(/\D/g, '').slice(0, 5);
    setter(value);
  };

  return (
    <div className="max-w-4xl mx-auto p-4 bg-white shadow-lg">
    <div className="max-w-4xl mx-auto p-4 bg-white shadow-lg">
      Web form generated by scan of PDF by Claude
    </div>    
      <div className="flex justify-between mb-4">
        <div>
          <h1 className="text-2xl font-bold">AB Trucking</h1>
          <p>10 Burma Rd, Oakland, CA 94607</p>
          <p>Phone: 510-835-0930</p>
          <p>Email: dispatch@abtruck.com</p>
        </div>
        <div className="text-right">
          <h2 className="text-xl font-semibold">Straight Bill of Lading</h2>
          <p>Container #: <input type="text" className="border px-2" /></p>
          <p>BOL #: <input type="text" className="border px-2" /></p>
          <p>Customer Ref #: <input type="text" className="border px-2" /></p>
          <p>Carrier Ref #: <input type="text" className="border px-2" /></p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-4">
        <div className="border p-2">
          <h3 className="font-semibold">Pick Up from</h3>
          <input type="text" className="w-full border px-2 mb-2" placeholder="Name" />
          <input type="text" className="w-full border px-2 mb-2" placeholder="Address" />
          <input type="text" className="w-full border px-2 mb-2" placeholder="City" />
          <select className="w-full border px-2 mb-2">
            <option value="">Select State</option>
            <option value="CA">California</option>
            {/* Add other states here */}
          </select>
          <input 
            type="text" 
            className="w-full border px-2" 
            placeholder="ZIP" 
            value={pickupZip}
            onChange={handleZipChange(setPickupZip)}
          />
        </div>
        <div className="border p-2">
          <h3 className="font-semibold">Delivery To</h3>
          <input type="text" className="w-full border px-2 mb-2" placeholder="Name" />
          <input type="text" className="w-full border px-2 mb-2" placeholder="Address" />
          <input type="text" className="w-full border px-2 mb-2" placeholder="City" />
          <select className="w-full border px-2 mb-2">
            <option value="">Select State</option>
            <option value="CA">California</option>
            {/* Add other states here */}
          </select>
          <input 
            type="text" 
            className="w-full border px-2" 
            placeholder="ZIP" 
            value={deliveryZip}
            onChange={handleZipChange(setDeliveryZip)}
          />
        </div>
      </div>

      <div className="mb-4">
        <h3 className="font-semibold">Ship Line information</h3>
        <table className="w-full border-collapse border">
          <thead>
            <tr className="bg-gray-100">
              <th className="border p-2">Container Number</th>
              <th className="border p-2">Shipline</th>
              <th className="border p-2">Vessel</th>
              <th className="border p-2">Container Size/Type</th>
              <th className="border p-2">Chassis No.</th>
              <th className="border p-2">Seal No.</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border p-2"><input type="text" className="w-full" /></td>
              <td className="border p-2"><input type="text" className="w-full" /></td>
              <td className="border p-2"><input type="text" className="w-full" /></td>
              <td className="border p-2">
                <select className="w-full border px-2">
                  <option value="">Select Type</option>
                  <option value="type1">Type 1</option>
                  <option value="type2">Type 2</option>
                  <option value="type3">Type 3</option>
                </select>
              </td>
              <td className="border p-2"><input type="text" className="w-full" /></td>
              <td className="border p-2"><input type="text" className="w-full" /></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="mb-4">
        <h3 className="font-semibold">Cargo Information</h3>
        <table className="w-full border-collapse border">
          <thead>
            <tr className="bg-gray-100">
              <th className="border p-2">Units</th>
              <th className="border p-2">Hazmat</th>
              <th className="border p-2">Cargo Description</th>
              <th className="border p-2">Cargo Weight</th>
              <th className="border p-2">Gross / Tare Weight</th>
              <th className="border p-2">Weight Ticket</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border p-2"><input type="text" className="w-full" /></td>
              <td className="border p-2"><input type="text" className="w-full" /></td>
              <td className="border p-2"><input type="text" className="w-full" /></td>
              <td className="border p-2"><input type="text" className="w-full" /></td>
              <td className="border p-2"><input type="text" className="w-full" /></td>
              <td className="border p-2"><input type="text" className="w-full" /></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="mb-4">
        <h3 className="font-semibold">Delivery Information</h3>
        <table className="w-full border-collapse border">
          <thead>
            <tr className="bg-gray-100">
              <th className="border p-2">Appointment Date and Time</th>
              <th className="border p-2">Arrival at Shipper</th>
              <th className="border p-2">Loading Start/End</th>
              <th className="border p-2">Departure at Shipper</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border p-2"><DateTimeDropdown name="appointment" /></td>
              <td className="border p-2"><DateTimeDropdown name="arrival" /></td>
              <td className="border p-2"><DateTimeDropdown name="loading" /></td>
              <td className="border p-2"><DateTimeDropdown name="departure" /></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="mb-4">
        <h3 className="font-semibold">Delivery Notes</h3>
        <textarea className="w-full border p-2" rows="3"></textarea>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-4">
        <div>
          <h3 className="font-semibold">Carrier/Driver</h3>
          <input type="text" className="w-full border px-2 mb-2" placeholder="Signature" />
          <input type="text" className="w-full border px-2 mb-2" placeholder="Printed Name" />
          <DateTimeDropdown name="carrierDate" />
        </div>
        <div>
          <h3 className="font-semibold">Shipper/Consignee</h3>
          <input type="text" className="w-full border px-2 mb-2" placeholder="Signature" />
          <input type="text" className="w-full border px-2 mb-2" placeholder="Printed Name" />
          <DateTimeDropdown name="shipperDate" />
        </div>
      </div>

      <p className="text-sm">
        This is to certify that the above named materials are properly classified, packaged, marked, and labeled, and are in proper condition for transportation according to the applicable regulations of the DOT. Shipper agrees that the custody and carriage of goods identified shall be subject to the terms and conditions on the reverse (or page 2).
      </p>
    </div>
  );
};

export default BillOfLadingForm;
